fix

diff --git a/.github/workflows/env-array.yml b/.github/workflows/env-array.yml
--- a/.github/workflows/env-array.yml
+++ b/.github/workflows/env-array.yml
@@ -1,27 +1,70 @@
-name: mytest
+name: env-array
 
 on:
   workflow_dispatch:
     inputs:
-      cluster_name:
+      build:
         description: Build
-        default: windows
-        required: false
+        default: all my_windows-10-enterprise-x64-eval-libvirt ubuntu-20.04-server-amd64-libvirt
+        required: true
 
 env:
-  BUILDS: |-
-    [
-      "aaa",
-      "bbb",
-      "azzz"
-    ]
+  BUILDS_LIST: >-
+    my_windows-10-enterprise-x64-eval-libvirt
+    my_windows-10-enterprise-x64-eval-virtualbox
+    ubuntu-18.04-server-amd64-libvirt
+    ubuntu-18.04-server-amd64-virtualbox
+    ubuntu-20.04-desktop-amd64-libvirt
+    ubuntu-20.04-desktop-amd64-virtualbox
+    ubuntu-20.04-server-amd64-libvirt
+    ubuntu-20.04-server-amd64-virtualbox
+    windows-10-enterprise-x64-eval-libvirt
+    windows-10-enterprise-x64-eval-virtualbox
+    windows-server-2012_r2-standard-x64-eval-libvirt
+    windows-server-2012_r2-standard-x64-eval-virtualbox
+    windows-server-2016-standard-x64-eval-libvirt
+    windows-server-2016-standard-x64-eval-virtualbox
+    windows-server-2019-standard-x64-eval-libvirt
+    windows-server-2019-standard-x64-eval-virtualbox
+    windows-server-2022-standard-x64-eval-libvirt
+    windows-server-2022-standard-x64-eval-virtualbox
 
 
 jobs:
-  create:
+  generate-cluster-matrix:
+    name: "Generate cluster matrix"
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
-      - name: Test
+      - name: Get Matrix Builds
+        id: set-matrix
         run: |
-          set -eux
-          for I in ${BUILDS[@]}; do echo $I; done
+          set -euo pipefail
+          declare -a BUILDS_MATRIX
+          read -a -r BUILDS <<< "${BUILDS_LIST}"
+          for BUILD_BOX in "${BUILDS[@]}" ; do
+            if [[ "${{ github.event.inputs.build }}" =~ ${BUILD_BOX} || "${{ github.event.inputs.build }}" = "all" ]] ; then
+              echo "***🔎 ${BUILD_BOX}"
+              BUILDS_MATRIX+=("${BUILD_BOX}")
+            fi
+          done
+
+          jq --compact-output --null-input '$ARGS.positional' --args "${BUILDS_MATRIX[@]}"
+          echo "::set-output name=matrix::$( jq --compact-output --null-input '$ARGS.positional' --args "${BUILDS_MATRIX[@]}" )"
+
+  build-pipeline:
+    name: "*"
+    runs-on: ubuntu-latest
+    needs: generate-cluster-matrix
+    concurrency:
+      group: build-pipeline-${{ matrix.stage }}
+    strategy:
+      # Do not cancel matrix jobs if one of them fails
+      fail-fast: false
+      matrix:
+        stage: ${{ fromJSON(needs.generate-cluster-matrix.outputs.matrix) }}
+    steps:
+      - name: Show stage
+        run: |
+          echo ${{ matrix.stage }}
