t2

diff --git a/.github/workflows/mytest.yml b/.github/workflows/mytest.yml
--- a/.github/workflows/mytest.yml
+++ b/.github/workflows/mytest.yml
@@ -1,40 +1,43 @@
 name: mytest
 
+# workflow_dispatch - do just create or just delete. Both with proper dependency + stop if create fail!
+
+# Push to master - run create and always delete
+
+
 on:
   workflow_dispatch:
     inputs:
       version:
         description: Action
-        default: delete
+        default: create, delete
         required: true
-env:
-  test: "12345"
+  push:
+    branches:
+      - master
+    paths:
+      - .github/workflows/mytest.yml
 
 jobs:
-  mysecret:
+  create:
     runs-on: ubuntu-latest
     steps:
-      - name: Test
-        env: # Or as an environment variable
-          ENV_SECRET: ${{ secrets.ENV_SECRET }}
-          TEST_SECRET: ${{ secrets.TEST_SECRET }}
+      - name: Test - create
+        if: ${{ contains(github.event.inputs.version, 'create') || ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) }}
         run: |
           set -x
           echo ${{ github.event.inputs.version }}
-          echo "${ENV_SECRET}"
-          echo "${ENV_SECRET}" > /tmp/del
-          cat /tmp/del
-          ls -la /tmp/del
-          rm /tmp/del
-          env | grep ENV_SECRET || true
-          echo "Secret_env: env_secret_12345"
-          echo "${TEST_SECRET}"
-          echo "${TEST_SECRET}" > /tmp/del
-          cat /tmp/del
-          ls -la /tmp/del
-          env | grep TEST_SECRET || true
-          echo "Secret_test: test_secret_12345"
-          env > /tmp/del
-          grep SECRET /tmp/del || true
-          echo "::add-mask::${{ secrets.MASK_TEST }}"
-          echo "mask_test_12345"
+          exit 0
+          #exit 1
+
+  delete:
+    runs-on: ubuntu-latest
+    needs: create
+    if: ${{ ( contains(github.event.inputs.version, 'delete') && success() ) || ( github.event_name == 'push' && github.ref == 'refs/heads/master' && always() ) }}
+    steps:
+      - name: Test - delete
+        run: |
+          set -x
+          echo ${{ github.event.inputs.version }}
+          #exit 0
+          exit 1
